"""add room is_external and lesson travel buffers

Revision ID: c2a5a324d8e0
Revises: f7a93b4c2d18
Create Date: 2026-05-16 12:03:22.660582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2a5a324d8e0"
down_revision: str | Sequence[str] | None = "f7a93b4c2d18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lessons",
        sa.Column(
            "pre_buffer_minutes", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column(
        "lessons",
        sa.Column(
            "post_buffer_minutes", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column(
        "rooms",
        sa.Column("is_external", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "is_external")
    op.drop_column("lessons", "post_buffer_minutes")
    op.drop_column("lessons", "pre_buffer_minutes")
    # ### end Alembic commands ###
